name: Sync Github Advisories Pull Request

on: [ push ]

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
      - name: Install ruby dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Update Github Advisories branch
        env:
          GH_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch sync_github_advisories
          bundle exec rake sync_github_advisories
          git add gems
          git commit -m "Sync Github Advisories"
          git push origin sync_github_advisories
